# Generated by Django 2.1.7 on 2019-03-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('msv', models.CharField(max_length=20)),
                ('lop', models.TextField()),
                ('ngaysinh', models.TimeField()),
            ],
        ),
    ]
