# Generated by Django 2.1.7 on 2019-03-06 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinhvien',
            name='ngaysinh',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
